const UserActionTypes = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SIGN_UP_START: "SIGN_UP_START",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
    SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
    VERIFY_START: "VERIFY_START",
    VERIFY_FAILED: "VERIFY_FAILED",
    VERIFY_ACCOUNT: "VERIFY_ACCOUNT",
};

export default UserActionTypes;
